apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-external-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: services-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
  data:
  - secretKey: PGDATABASE
    remoteRef:
      key: /services/prlbackend/prod/pgusername
  - secretKey: PGPASSWORD
    remoteRef:
      key: /services/prlbackend/prod/pgpassword
  - secretKey: PGUSER
    remoteRef:
      key: /services/prlbackend/prod/pgusername
