# Field to add ArgoCD applications to ArgoCD itself. This will automatically be applied by ArgoCD upon commits made to the main branch
argocd_applications:
  argocd_namespace: argocd
  default_sync_policy:
    syncPolicy:
      automated:
        selfHeal: true
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
  entries:
    - name: argocd
      deployment_namespace: argocd
      project: default
      destination: in-cluster
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          revision: main
          ref: values
        - repourl: https://chartmuseum.library.ucla.edu
          chart: argo-cd
          revision: 5.31.0
          valueFiles:
            - $values/infrastructure/argocd.library.ucla.edu/values.yaml
            - $values/infrastructure/argocd.library.ucla.edu/values-ucla.yaml
    - name: test-prl-harvester
      deployment_namespace: test-prl-harvester
      project: default
      destination: testsoftwaredev
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: teams/services/prl_harvester/overlays/test
          revision: main
    - name: prod-prl-harvester
      deployment_namespace: prod-prl-harvester
      project: default
      destination: prodsoftwaredev
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: teams/services/prl_harvester/overlays/prod
          revision: main

traefik_config:
  middleware:
    ipranges:
      - 164.67.40.0/24
      - 164.67.48.0/24
  ingressroutes:
    domain: argocd.library.ucla.edu

selfsigned_issuer:
  enabled: true

external_secrets:
  refresh_interval: 10m
  enabled: true
  secretstoreref_name: argocd-clustersecretstore
  secretstoreref_type: ClusterSecretStore
  server:
    secretkey: /devsupport/argocd/server/server_secretkey
  clusters:
    - base: /devsupport/argocd/cluster
      name: prodsoftwaredev
    - base: /devsupport/argocd/cluster
      name: prodeks
    - base: /devsupport/argocd/cluster
      name: testsoftwaredev
  ldap:
    enabled: true
    bind_dn_key: /devsupport/argocd/ldap/uclalibrary_bind_dn
    bind_dn_pw: /devsupport/argocd/ldap/uclalibrary_bind_pw
    ca_crt: /devsupport/argocd/ldap/uclalibrary_ad_ca_crt
  slack:
    enabled: true
    token: /devsupport/argocd/slack/token
