---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signage
  namespace: argocd
  labels:
    team: systems
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        namespace_team: systems
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  project: default
  destination:
    name: {{ .Values.spec.destination.server }}
    namespace: signageprod
  sources:
    - repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.0.4
      chart: signage
      helm:
        valueFiles:
          - $values/charts/prod-signage-values.yaml
    - repoURL: "https://github.com/UCLALibrary/digital-signage-hours"
      targetRevision: main
      ref: values
