---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oral-history-staff-ui
  namespace: argocd
  labels:
    team: systems
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        namespace_team: systems
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  project: default
  destination:
    name: {{ .Values.spec.destination.server }}
    namespace: oh-staffprod
  sources:
    - repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 0.8.2
      chart: oh-staff
      helm:
        valueFiles:
          - $values/charts/prod-ohstaff-values.yaml
    - repoURL: "https://github.com/UCLALibrary/oral-history-staff-ui"
      targetRevision: main
      ref: values
