# Voyager Archive Ethno
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voyager-archive-ethno
  namespace: argocd
  labels:
    team: systems
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        namespace_team: systems
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  project: default
  destination:
    name: {{ .Values.spec.destination.server }}
    namespace: voyager-archiveprod
  sources:
    - repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.1.0
      chart: voyager-archive
      helm:
        valueFiles:
          - $values/charts/prod-ethnovoyagerarchive-values.yaml
    - repoURL: "https://github.com/UCLALibrary/voyager-archive"
      targetRevision: main
      ref: values

# Voyager Archive FTVA
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voyager-archive-ftva
  namespace: argocd
  labels:
    team: systems
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        namespace_team: systems
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  project: default
  destination:
    name: {{ .Values.spec.destination.server }}
    namespace: voyager-archiveprod
  sources:
    - repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.1.0
      chart: voyager-archive
      helm:
        valueFiles:
          - $values/charts/prod-ftvavoyagerarchive-values.yaml
    - repoURL: "https://github.com/UCLALibrary/voyager-archive"
      targetRevision: main
      ref: values

# Voyager Archive UCLA
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voyager-archive-ucla
  namespace: argocd
  labels:
    team: systems
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        namespace_team: systems
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  project: default
  destination:
    name: {{ .Values.spec.destination.server }}
    namespace: voyager-archiveprod
  sources:
    - repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.1.0
      chart: voyager-archive
      helm:
        valueFiles:
          - $values/charts/prod-uclavoyagerarchive-values.yaml
    - repoURL: "https://github.com/UCLALibrary/voyager-archive"
      targetRevision: main
      ref: values
