# Field to add ArgoCD applications to ArgoCD itself. This will automatically be applied by ArgoCD upon commits made to the main branch
argocd_applications:
  argocd_namespace: argocd
  default_sync_policy:
    syncPolicy:
      automated:
        selfHeal: true
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
  entries:
    - name: prod-prl-harvester
      deployment_namespace: prod-prl-harvester
      project: default
      destination: prodsoftwaredev
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: teams/services/prl_harvester/overlays/prod
          revision: main
    - name: prod-cantaloupe
      deployment_namespace: prod-cantaloupe
      project: default
      destination: prodeks
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: prod/prod-cantaloupe
          revision: main
    - name: prod-fester
      deployment_namespace: prod-fester
      project: default
      destination: prodeks
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: prod/prod-fester
          revision: main
    - name: prod-hauth
      deployment_namespace: prod-hauth
      project: default
      destination: prodeks
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: prod/prod-hauth
          revision: main
    - name: prod-libcalproxy
      deployment_namespace: prod-libcalproxy
      project: default
      destination: prodeks
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: prod/prod-libcalproxy
          revision: main
    - name: prod-ingest-fester
      deployment_namespace: prod-ingest-fester
      project: default
      destination: prodsoftwaredev
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: prod/prod-ingest-fester
          revision: main
    - name: frontend-prod-iiif
      deployment_namespace: frontend-prod-iiif
      project: default
      destination: prodeks
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: prod/frontend-prod-iiif
          revision: main
    - name: frontend-prod-ingest-iiif
      deployment_namespace: frontend-prod-ingest-iiif
      project: default
      destination: prodsoftwaredev
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: prod/frontend-prod-ingest-iiif
          revision: main
