# Field to add ArgoCD applications to ArgoCD itself. This will automatically be applied by ArgoCD upon commits made to the main branch
argocd_applications:
  argocd_namespace: argocd
  default_sync_policy:
    syncPolicy:
      automated:
        selfHeal: true
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
  entries:
    - name: oral-history-staff-ui
      deployment_namespace: oh-staffprod
      project: default
      destination: prodsoftwaredev
      sources:
        - repourl: https://github.com/UCLALibrary/oral-history-staff-ui
          path: charts
          revision: HEAD
          valueFiles:
            - prod-ohstaff-values.yaml
    - name: voyager-archive-ethno
      deployment_namespace: voyager-archiveprod
      project: default
      destination: prodsoftwaredev
      sources:
        - repourl: https://github.com/UCLALibrary/voyager-archive
          path: charts
          revision: HEAD
          valueFiles:
            - prod-ethnovoyagerarchive-values.yaml
    - name: voyager-archive-ftva
      deployment_namespace: voyager-archiveprod
      project: default
      destination: prodsoftwaredev
      sources:
        - repourl: https://github.com/UCLALibrary/voyager-archive
          path: charts
          revision: HEAD
          valueFiles:
            - prod-ftvavoyagerarchive-values.yaml
    - name: voyager-archive-ucla
      deployment_namespace: voyager-archiveprod
      project: default
      destination: prodsoftwaredev
      sources:
        - repourl: https://github.com/UCLALibrary/voyager-archive
          path: charts
          revision: HEAD
          valueFiles:
            - prod-uclavoyagerarchive-values.yaml
    - name: terra
      deployment_namespace: terraprod
      namespace_team: systems
      project: default
      destination: prodrke01
      sources:
        - repourl: https://chartmuseum.library.ucla.edu
          chart: terra
          revision: 0.3.2
          valueFiles:
            - $values/charts/prod-terra-values.yaml
        - repourl: https://github.com/UCLALibrary/terra
          revision: main
          ref: values
