# Field to add ArgoCD applications to ArgoCD itself. This will automatically be applied by ArgoCD upon commits made to the main branch
argocd_applications:
  argocd_namespace: argocd
  default_sync_policy:
    syncPolicy:
      automated:
        selfHeal: true
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
  entries:
    - name: prod-prl-harvester
      deployment_namespace: prod-prl-harvester
      project: default
      destination: prodsoftwaredev
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
      sources:
        - repourl: https://github.com/UCLALibrary/gitops_kubernetes.git
          path: teams/services/prl_harvester/overlays/prod
          revision: main
