---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
  annotations: {}
spec:
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  project: default
  destination:
    name: testrke01
    namespace: reloader
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      targetRevision: 2.1.2 #v1.4.1
      chart: reloader
