# Test Validator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-validator
  namespace: argocd
  labels:
    team: services
  annotations: {}
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        namespace_team: services
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  project: default
  destination:
    name: {{ .Values.spec.destination.rke.test.server }}
    namespace: test-validator
  sources:
    - repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.1.4
      chart: uclalib-helm-generic
      helm:
        valueFiles:
          - $values/test-validator.yaml
    - repoURL: "https://github.com/UCLALibrary/validation-service"
      targetRevision: test-validator
      ref: values

# Prod Validator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-validator
  namespace: argocd
  labels:
    team: services
  annotations: {}
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        namespace_team: services
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  project: default
  destination:
    name: {{ .Values.spec.destination.rke.prod.server }}
    namespace: prod-validator
  sources:
    - repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.1.3
      chart: uclalib-helm-generic
      helm:
        valueFiles:
          - $values/prod-validator.yaml
    - repoURL: "https://github.com/UCLALibrary/validation-service"
      targetRevision: prod-validator
      ref: values
