{{- if .Values.traefik_config.middleware }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: argocd-whitelist-ipranges
spec:
  ipWhiteList:
    sourceRange: {{ .Values.traefik_config.ipranges }}
{{- end }}
