apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fester
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: services-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: fester-secrets
  data:
  - secretKey: FESTER_S3_ACCESS_KEY
    remoteRef:
      key: /services/prodeks/prod-fester/fester_s3_access_key
  - secretKey: FESTER_S3_SECRET_KEY
    remoteRef:
      key: /services/prodeks/prod-fester/fester_s3_secret_key
