apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
  name: frontend-prod-iiif
  namespace: prod-argocd
spec:
  destination:
    namespace: frontend-prod-iiif
    server: https://rancher.library.ucla.edu/k8s/clusters/c-t8h8s
  project: iiif
  source:
    path: prod/frontend-prod-iiif
    repoURL: https://github.com/UCLALibrary/gitops_kubernetes
    targetRevision: main
  syncPolicy:
    automated: {}
