apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: softwaredev-services-firehose
  name: prod-cantaloupe
  namespace: prod-argocd
spec:
  destination:
    namespace: prod-cantaloupe
    server: https://rancher.library.ucla.edu/k8s/clusters/c-t8h8s
  project: iiif
  source:
    path: prod/prod-cantaloupe
    repoURL: https://github.com/UCLALibrary/gitops_kubernetes
    targetRevision: main
  syncPolicy:
    automated: {}
