{{- if .Values.argocd_applications.entries }}
{{- range $v := .Values.argocd_applications.entries }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $v.name }}
  namespace: {{ $.Values.argocd_applications.argocd_namespace }}
  annotations:
{{ $v.annotations | default dict | toYaml| indent 4 }}
spec:
  syncPolicy:
{{- if $v.namespace_team }}
    managedNamespaceMetadata:
      labels:
        namespace_team: {{ $v.namespace_team }}
{{- end }}
{{ $v.syncPolicy | default $.Values.argocd_applications.default_sync_policy.syncPolicy | toYaml | indent 4 }}
  project: {{ $v.project }}
  destination:
    name: {{ $v.destination }}
    namespace: {{ $v.deployment_namespace }}
  {{- if $v.sources }}
  sources:
  {{- range $w := $v.sources }}
    - repoURL: {{ $w.repourl }}
      targetRevision: {{ $w.revision }}
      {{- if $w.path }}
      path: {{ $w.path }}
      {{- else if $w.ref }}
      ref: {{ $w.ref }}
      {{- else }}
      chart: {{ $w.chart }}
      {{- end }}
      {{- if $w.valueFiles }}
      helm:
        valueFiles: {{ $w.valueFiles }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
