{{- if .Values.external_secrets.clusters }}
{{- range $v := .Values.external_secrets.clusters }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-cluster-{{ $v.name }}
  labels:
    argocd.argoproj.io/secret-type: cluster
spec:
  refreshInterval: {{ $.Values.external_secrets.refresh_interval }}
  secretStoreRef:
    name: {{ $.Values.external_secrets.secretstoreref_name }}
    kind: {{ $.Values.external_secrets.secretstoreref_type }}
  target:
    name: argocd-cluster-{{ $v.name }}
  data:
  - secretKey: config
    remoteRef:
      key: {{ $v.base }}/{{ $v.name }}/token
  - secretKey: server
    remoteRef:
      key: {{ $v.base }}/{{ $v.name }}/url
  - secretKey: name
    remoteRef:
      key: {{ $v.base }}/{{ $v.name }}/name
{{- end }}
{{- end }}
