{{- if .Values.argocd_applications.entries }}
{{- range $v := .Values.argocd_applications.entries }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $v.name }}
  namespace: {{ $v.deployment_namespace }}
spec:
  project: {{ $v.project }}
  destination:
    server: {{ $v.destination }}
    namespace: {{ $.Values.argocd_namespace }}
  {{- if $v.sources }}
  {{- range $w := $v.sources }}
  sources:
    - repoURL: {{ $w.repourl }}
      targetRevision: {{ $w.revision }}
      {{- if $w.path }}
      path: {{ $w.path }}
      {{ else }}
      chart: {{ $w.chart }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
