# -- Deploy Argo CD Applications within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
applications:
# PRL Application
  - name: prod-prl-harvester
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: services
    additionalAnnotations: {}
    project: default
    sources:
      - chart: uclalib-helm-generic
        repoURL: https://chartmuseum.library.ucla.edu
        targetRevision: 1.0.1
        helm:
          valueFiles:
          - $values/apps/services-team-value-files/prod-prl-harvester.yaml
      - ref: values
        repoURL: https://github.com/UCLALibrary/gitops_kubernetes
        targetRevision: main
    destination:
      name: prodrke01
      namespace: prod-prl-harvester
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: services
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# HAuth Application
  - name: prod-hauth
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: services
    additionalAnnotations: {}
    project: default
    sources:
      - chart: uclalib-helm-generic
        repoURL: https://chartmuseum.library.ucla.edu
        targetRevision: 1.0.4
        helm:
          valueFiles:
          - $values/apps/services-team-value-files/prod-hauth.yaml
      - ref: values
        repoURL: https://github.com/UCLALibrary/gitops_kubernetes
        targetRevision: main
    destination:
      name: prod-eks-services-team
      namespace: prod-hauth
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: services
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# LibCalProxy Application
  - name: prod-libcalproxy
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: services
    additionalAnnotations: {}
    project: default
    sources:
      - chart: uclalib-helm-generic
        repoURL: https://chartmuseum.library.ucla.edu
        targetRevision: 1.0.1
        helm:
          valueFiles:
          - $values/apps/services-team-value-files/prod-libcalproxy.yaml
      - ref: values
        repoURL: https://github.com/UCLALibrary/gitops_kubernetes
        targetRevision: main
    destination:
      name: prod-eks-services-team
      namespace: prod-libcalproxy
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: services
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Fester Application
  - name: prod-fester
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: services
    additionalAnnotations: {}
    project: default
    sources:
      - chart: uclalib-helm-generic
        repoURL: https://chartmuseum.library.ucla.edu
        targetRevision: 1.0.1
        helm:
          valueFiles:
          - $values/apps/services-team-value-files/prod-fester.yaml
      - ref: values
        repoURL: https://github.com/UCLALibrary/gitops_kubernetes
        targetRevision: main
    destination:
      name: prod-eks-services-team
      namespace: prod-fester
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: services
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Cantaloupe Application
  - name: prod-cantaloupe
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: services
    additionalAnnotations: {}
    project: default
    sources:
      - chart: uclalib-helm-generic
        repoURL: https://chartmuseum.library.ucla.edu
        targetRevision: 1.0.4
        helm:
          valueFiles:
          - $values/apps/services-team-value-files/prod-cantaloupe.yaml
      - ref: values
        repoURL: https://github.com/UCLALibrary/gitops_kubernetes
        targetRevision: main
    destination:
      name: prod-eks-services-team
      namespace: prod-cantaloupe
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: services
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
  - name: prod-sinai-cantaloupe
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: services
    additionalAnnotations: {}
    project: default
    sources:
      - chart: uclalib-helm-generic
        repoURL: https://chartmuseum.library.ucla.edu
        targetRevision: 1.0.1
        helm:
          valueFiles:
          - $values/apps/services-team-value-files/prod-sinai-cantaloupe.yaml
      - ref: values
        repoURL: https://github.com/UCLALibrary/gitops_kubernetes
        targetRevision: main
    destination:
      name: prod-eks-services-team
      namespace: prod-sinai-cantaloupe
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: services
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# iiif.library.ucla.edu ingress
  - name: frontend-prod-iiif
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: services
    additionalAnnotations: {}
    project: default
    sources:
      - chart: uclalib-helm-generic
        repoURL: https://chartmuseum.library.ucla.edu
        targetRevision: 1.0.1
        helm:
          valueFiles:
          - $values/apps/services-team-value-files/frontend-prod-iiif.yaml
      - ref: values
        repoURL: https://github.com/UCLALibrary/gitops_kubernetes
        targetRevision: main
    destination:
      name: prod-eks-services-team
      namespace: frontend-prod-iiif
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: services
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Prod ingest fester
  - name: prod-ingest-fester
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: services
    additionalAnnotations: {}
    project: default
    sources:
      - chart: uclalib-helm-generic
        repoURL: https://chartmuseum.library.ucla.edu
        targetRevision: 1.0.1
        helm:
          valueFiles:
          - $values/apps/services-team-value-files/prod-ingest-fester.yaml
      - ref: values
        repoURL: https://github.com/UCLALibrary/gitops_kubernetes
        targetRevision: main
    destination:
      name: prodrke01
      namespace: prod-ingest-fester
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: services
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20

#
#
# -- Deploy Argo CD Projects within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
projects: []
# - name: guestbook
#   namespace: argocd
#   additionalLabels: {}
#   additionalAnnotations: {}
#   permitOnlyProjectScopedClusters: false
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
#   description: Example Project
#   sourceRepos:
#   - '*'
#   destinations:
#   - namespace: guestbook
#     server: https://kubernetes.default.svc
#   clusterResourceWhitelist: []
#   clusterResourceBlacklist: []
#   namespaceResourceBlacklist:
#   - group: ''
#     kind: ResourceQuota
#   - group: ''
#     kind: LimitRange
#   - group: ''
#     kind: NetworkPolicy
#     orphanedResources: {}
#     roles: []
#   namespaceResourceWhitelist:
#   - group: 'apps'
#     kind: Deployment
#   - group: 'apps'
#     kind: StatefulSet
#   orphanedResources: {}
#   roles: []
#   syncWindows:
#   - kind: allow
#     schedule: '10 1 * * *'
#     duration: 1h
#     applications:
#     - '*-prod'
#     manualSync: true
#   signatureKeys:
#   - keyID: ABCDEF1234567890
#   sourceNamespaces:
#   - argocd

# -- Deploy Argo CD ApplicationSets within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
applicationsets: []
# - name: guestbook
#   namespace: argocd
#   additionalLabels: {}
#   additionalAnnotations: {}
#   # See PR #10026 (ArgoCD v2.5 or later)
#   # goTemplate: false
#   generators:
#   - git:
#       repoURL: https://github.com/argoproj/argocd-example-apps.git
#       revision: HEAD
#       directories:
#       - path: guestbook
#       - path: kustomize-*
#   # Progressive Syncs is an experimental feature and it must be explicitly enabled
#   # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
#   strategy:
#     type: RollingSync
#     rollingSync:
#       steps:
#       - matchExpressions:
#         - key: project
#           operator: In
#           values:
#           - guestbook
#       - matchExpressions:
#         - key: project
#           operator: In
#           values:
#           - kustomize-foo
#           - kustomize-bar
#   template:
#     metadata:
#       name: '{{path.basename}}'
#       labels:
#         project: '{{path.basename}}'
#       annotations: {}
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/argoproj/argocd-example-apps.git
#         targetRevision: HEAD
#         path: '{{path}}'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: default
#       syncPolicy:
#         automated:
#           prune: false
#           selfHeal: false
#       ignoreDifferences:
#       - group: apps
#         kind: Deployment
#         jsonPointers:
#         - /spec/replicas
#       info:
#       - name: url
#         value: https://argoproj.github.io/
#   syncPolicy:
#     # Set Application finalizer
#     preserveResourcesOnDeletion: false

# --  Deploy Argo CD Applications/ApplicationSets/Projects within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
itemTemplates: []
# - items:
#     - name: my-appset
#       generators: &generators
#         - list:
#             elements:
#               - cluster: engineering-dev
#                 url: https://1.2.3.4
#               - cluster: engineering-prod
#                 url: https://2.4.6.8
#               - cluster: finance-preprod
#                 url: https://9.8.7.6
#   template:
#     apiVersion: argoproj.io/v1alpha1
#     kind: ApplicationSet
#     metadata:
#       name: "{{ .name }}"
#     spec:
#       generators: *generators
#       template:
#         metadata:
#           name: "{{`{{cluster}}`}}-guestbook"
#         spec:
#           project: my-project
#           source:
#             repoURL: https://github.com/infra-team/cluster-deployments.git
#             targetRevision: HEAD
#             path: guestbook/{{`{{cluster}}`}}
#           destination:
#             server: "{{`{{cluster}}`}}"
#             namespace: guestbook
# - items:
#     - name: my-appset
#       generators:
#         - list:
#             elements:
#               - cluster: engineering-dev
#                 url: https://1.2.3.4
#               - cluster: engineering-prod
#                 url: https://2.4.6.8
#               - cluster: finance-preprod
#                 url: https://9.8.7.6
#   template: |-
#     apiVersion: argoproj.io/v1alpha1
#     kind: ApplicationSet
#     metadata:
#       name: {{ .name }}
#     spec:
#       generators: {{ toYaml .generators | nindent 4 }}
#       template:
#         metadata:
#           name: '{{`{{cluster}}`}}-guestbook'
#         spec:
#           project: my-project
#           source:
#             repoURL: https://github.com/infra-team/cluster-deployments.git
#             targetRevision: HEAD
#             path: guestbook/{{`{{cluster}}`}}
#           destination:
#             server: '{{`{{cluster}}`}}'
#             namespace: guestbook

# -- Deploy Argo UI Extensions within this helm release
# @default -- `[]` (See [values.yaml])
## This function in tech preview stage, do expect unstability or breaking changes in newer versions. Bump image.tag if necessary.
## Ref: https://github.com/argoproj-labs/argocd-extensions
extensions: []
  # - name: example
  #   namespace: argocd
  #   additionalLabels: {}
  #   additionalAnnotations: {}
  #   sources:
  #     - git:
  #         url: https://github.com/argoproj-labs/argocd-example-extension.git
  #     - web:
  #         url: https://github.com/argoproj-labs/argocd-example-extension/releases/download/v0.1.0/extension.tar
