# -- Deploy Argo CD Applications within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
applications:
# Cataloging Statistics Application
  - name: cataloging-statistics
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: cataloging-statistics
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 0.0.5
      helm:
        valueFiles:
        - $values/charts/prod-catalogingstatistics-values.yaml
    - ref: values
      repoURL: https://github.com/UCLALibrary/cataloging-statistics
      targetRevision: main
    destination:
      name: prodrke01
      namespace: cataloging-statisticsprod
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# LBS Application
  - name: lbs
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: lbs
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 0.3.2
      helm:
        valueFiles:
        - $values/charts/prod-lbs-values.yaml
    - ref: values
      repoURL: https://github.com/UCLALibrary/LBS
      targetRevision: main
    destination:
      name: prodrke01
      namespace: lbsprod
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Voyager Archive Ethno
  - name: voyager-archive-ethno
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: voyager-archive
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.0.17
      helm:
        valueFiles:
        - $values/charts/prod-ethnovoyagerarchive-values.yaml
    - ref: values
      repoURL: https://github.com/UCLALibrary/voyager-archive
      targetRevision: main
    destination:
      name: prodrke01
      namespace: voyager-archiveprod
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Voyager Archive FTVA
  - name: voyager-archive-ftva
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: voyager-archive
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.0.17
      helm:
        valueFiles:
        - $values/charts/prod-ftvavoyagerarchive-values.yaml
    - ref: values
      repoURL: https://github.com/UCLALibrary/voyager-archive
      targetRevision: main
    destination:
      name: prodrke01
      namespace: voyager-archiveprod
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Voyager Archive UCLA
  - name: voyager-archive-ucla
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: voyager-archive
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.0.17
      helm:
        valueFiles:
        - $values/charts/prod-uclavoyagerarchive-values.yaml
    - ref: values
      repoURL: https://github.com/UCLALibrary/voyager-archive
      targetRevision: main
    destination:
      name: prodrke01
      namespace: voyager-archiveprod
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Terra
  - name: terra
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: terra
      helm:
        valueFiles:
        - $values/charts/prod-terra-values.yaml
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 0.4.0
    - ref: values
      repoURL: https://github.com/UCLALibrary/terra
      targetRevision: main
    destination:
      name: prodrke01
      namespace: terraprod
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Oral History Staff UI
  - name: oral-history-staff-ui
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: oh-staff
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 0.6.0
      helm:
        valueFiles:
        - $values/charts/prod-ohstaff-values.yaml
    - ref: values
      repoURL: https://github.com/UCLALibrary/oral-history-staff-ui
      targetRevision: main
    destination:
      name: prodrke01
      namespace: oh-staffprod
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Link Shortener Application
  - name: link-shortener
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: link-shortener
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.0.2
      helm:
        valueFiles:
        - $values/charts/prod-linkshortener-values.yaml
    - ref: values
      repoURL: https://github.com/UCLALibrary/link-shortener
      targetRevision: main
    destination:
      name: prodrke01
      namespace: link-shortenerprod
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# Digital Signage Application
  - name: signage
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: signage
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 1.0.1
      helm:
        valueFiles:
        - $values/charts/prod-signage-values.yaml
    - ref: values
      repoURL: https://github.com/UCLALibrary/digital-signage-hours
      targetRevision: main
    destination:
      name: prodrke01
      namespace: signageprod
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
# DLCS Export 
  - name: dlexport
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    additionalLabels:
      team: systems
    additionalAnnotations: {}
    project: default
    sources:
    - chart: dlexport
      repoURL: https://chartmuseum.library.ucla.edu
      targetRevision: 0.4.0
      helm:
        valueFiles:
        - $values/charts/prod-dlexport-values.yaml
    - ref: values
      repoURL: git@github.com:UCLALibrary/dlexport.git
      targetRevision: main
    destination:
      name: prodrke01
      namespace: dlexport
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          namespace_team: systems
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PruneLast=true
    revisionHistoryLimit: 20
#
#
# -- Deploy Argo CD Projects within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
projects: []
# - name: guestbook
#   namespace: argocd
#   additionalLabels: {}
#   additionalAnnotations: {}
#   permitOnlyProjectScopedClusters: false
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
#   description: Example Project
#   sourceRepos:
#   - '*'
#   destinations:
#   - namespace: guestbook
#     server: https://kubernetes.default.svc
#   clusterResourceWhitelist: []
#   clusterResourceBlacklist: []
#   namespaceResourceBlacklist:
#   - group: ''
#     kind: ResourceQuota
#   - group: ''
#     kind: LimitRange
#   - group: ''
#     kind: NetworkPolicy
#     orphanedResources: {}
#     roles: []
#   namespaceResourceWhitelist:
#   - group: 'apps'
#     kind: Deployment
#   - group: 'apps'
#     kind: StatefulSet
#   orphanedResources: {}
#   roles: []
#   syncWindows:
#   - kind: allow
#     schedule: '10 1 * * *'
#     duration: 1h
#     applications:
#     - '*-prod'
#     manualSync: true
#   signatureKeys:
#   - keyID: ABCDEF1234567890
#   sourceNamespaces:
#   - argocd

# -- Deploy Argo CD ApplicationSets within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
applicationsets: []
# - name: guestbook
#   namespace: argocd
#   additionalLabels: {}
#   additionalAnnotations: {}
#   # See PR #10026 (ArgoCD v2.5 or later)
#   # goTemplate: false
#   generators:
#   - git:
#       repoURL: https://github.com/argoproj/argocd-example-apps.git
#       revision: HEAD
#       directories:
#       - path: guestbook
#       - path: kustomize-*
#   # Progressive Syncs is an experimental feature and it must be explicitly enabled
#   # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
#   strategy:
#     type: RollingSync
#     rollingSync:
#       steps:
#       - matchExpressions:
#         - key: project
#           operator: In
#           values:
#           - guestbook
#       - matchExpressions:
#         - key: project
#           operator: In
#           values:
#           - kustomize-foo
#           - kustomize-bar
#   template:
#     metadata:
#       name: '{{path.basename}}'
#       labels:
#         project: '{{path.basename}}'
#       annotations: {}
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/argoproj/argocd-example-apps.git
#         targetRevision: HEAD
#         path: '{{path}}'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: default
#       syncPolicy:
#         automated:
#           prune: false
#           selfHeal: false
#       ignoreDifferences:
#       - group: apps
#         kind: Deployment
#         jsonPointers:
#         - /spec/replicas
#       info:
#       - name: url
#         value: https://argoproj.github.io/
#   syncPolicy:
#     # Set Application finalizer
#     preserveResourcesOnDeletion: false

# --  Deploy Argo CD Applications/ApplicationSets/Projects within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
itemTemplates: []
# - items:
#     - name: my-appset
#       generators: &generators
#         - list:
#             elements:
#               - cluster: engineering-dev
#                 url: https://1.2.3.4
#               - cluster: engineering-prod
#                 url: https://2.4.6.8
#               - cluster: finance-preprod
#                 url: https://9.8.7.6
#   template:
#     apiVersion: argoproj.io/v1alpha1
#     kind: ApplicationSet
#     metadata:
#       name: "{{ .name }}"
#     spec:
#       generators: *generators
#       template:
#         metadata:
#           name: "{{`{{cluster}}`}}-guestbook"
#         spec:
#           project: my-project
#           source:
#             repoURL: https://github.com/infra-team/cluster-deployments.git
#             targetRevision: HEAD
#             path: guestbook/{{`{{cluster}}`}}
#           destination:
#             server: "{{`{{cluster}}`}}"
#             namespace: guestbook
# - items:
#     - name: my-appset
#       generators:
#         - list:
#             elements:
#               - cluster: engineering-dev
#                 url: https://1.2.3.4
#               - cluster: engineering-prod
#                 url: https://2.4.6.8
#               - cluster: finance-preprod
#                 url: https://9.8.7.6
#   template: |-
#     apiVersion: argoproj.io/v1alpha1
#     kind: ApplicationSet
#     metadata:
#       name: {{ .name }}
#     spec:
#       generators: {{ toYaml .generators | nindent 4 }}
#       template:
#         metadata:
#           name: '{{`{{cluster}}`}}-guestbook'
#         spec:
#           project: my-project
#           source:
#             repoURL: https://github.com/infra-team/cluster-deployments.git
#             targetRevision: HEAD
#             path: guestbook/{{`{{cluster}}`}}
#           destination:
#             server: '{{`{{cluster}}`}}'
#             namespace: guestbook

# -- Deploy Argo UI Extensions within this helm release
# @default -- `[]` (See [values.yaml])
## This function in tech preview stage, do expect unstability or breaking changes in newer versions. Bump image.tag if necessary.
## Ref: https://github.com/argoproj-labs/argocd-extensions
extensions: []
  # - name: example
  #   namespace: argocd
  #   additionalLabels: {}
  #   additionalAnnotations: {}
  #   sources:
  #     - git:
  #         url: https://github.com/argoproj-labs/argocd-example-extension.git
  #     - web:
  #         url: https://github.com/argoproj-labs/argocd-example-extension/releases/download/v0.1.0/extension.tar
