resources: {}

fester:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 256Mi
  replicaCount: 1
  ingress:
    enabled: false
  image:
    repository: "uclalibrary/fester"
    tag: "1.2.2"
    imagePullSecrets:
      - name: services-dockerhub
  fester:
    env:
      FESTER_URL: "https://iiif.library.ucla.edu"
      FESTER_S3_BUCKET: "prod-iiif-fester-source"
      FESTER_S3_REGION: "us-west-2"
      FESTERIZE_VERSION: "0.4.2"
      IIIF_BASE_URL: "https://iiif.library.ucla.edu/iiif/2"
      AV_DEFAULT_AUDIO_THUMBNAIL_URL: "https://static.library.ucla.edu/audio_icon.svg"
      AV_DEFAULT_VIDEO_THUMBNAIL_URL: "https://static.library.ucla.edu/video_icon.svg"
    envSecrets:
      FESTER_S3_SECRET_KEY: "fester-secrets"
      FESTER_S3_ACCESS_KEY: "fester-secrets"
